### ISSUE TITLE
False positive for TYPO3\CMS\Core\Messaging\FlashMessage in Extension Scanner

### ISSUE THREAD

**Issue by PeaceSfiSh** [Tuurlijk/typo3scan#14]
The first definition in the file cms-scanner/config/Matcher/v7/ClassNameMatcher.php is for the "removed" class TYPO3\CMS\Core\Messaging\FlashMessage, but the class isn't removed, not even in v9.
With every use of FlashMessage::WARNING a false positive is shown.

The flash message handling was updated in ticket no #57382 (https://review.typo3.org/#/c/28912/)

The only removed class in v7 is TYPO3\CMS\Extbase\Mvc\Controller\FlashMessageContainer

**Comment by Tuurlijk** [comment]
Thanks, fixed in latest release
