### ISSUE TITLE
[FEATURE] Only display Breaking Changes in Reports

### ISSUE THREAD

**Issue by tomasnorre** [Tuurlijk/typo3scan#15]
Hi,

When maintaining bigger Projects (100+ extensions) the breaking changes have priority over deprecations. 

It would be could if one could add a Option parameter to only show Breaking changes.

I know that I should run the report on extension level too, but for progress monitoring and overview and aggregated report is really helpful. 

Let me know what you think, would be happy to help implementing if the idea gets a thumbs up.

**Comment by Tuurlijk** [comment]
sounds like a neat addition

**Comment by tomasnorre** [comment]
ok. Will into it and see if I can provide a Pull Request.

**Comment by mbrodala** [comment]
Generally a filter by type would be useful here.

**Comment by Tuurlijk** [comment]
We can add commandline options:
`--onlybreaking` / `--ob`
`--onlydeprecations` / `--od`

??

**Comment by mbrodala** [comment]
Or maybe `--only breaking,deprecation,...` if that isn't too hard to implement.

**Comment by Tuurlijk** [comment]
Yes, just saw that we have:
```php
    const TYPE_BREAKING = 'BREAKING';
    const TYPE_DEPRECATION = 'DEPRECATION';
    const TYPE_IMPORTANT = 'IMPORTANT';
    const TYPE_FEATURE = 'FEATURE';
```

**Comment by Tuurlijk** [comment]
Fixed with: https://github.com/Tuurlijk/typo3scan/releases/tag/1.5.0

**Comment by mbrodala** [comment]
@Tuurlijk Thanks a lot. :-)
