### ISSUE TITLE
HTML Report CSS

### ISSUE THREAD

**Issue by can0199** [Tuurlijk/typo3scan#17]
I recommend to add to the CSS for pre 
`overflow: auto `
to prevent this:
![bildschirmfoto 2019-01-18 um 09 49 15](https://user-images.githubusercontent.com/6803382/51375554-79e03000-1b06-11e9-810b-4e0111fe5ecc.png)

**Comment by Tuurlijk** [comment]
Yes, nice. Can you make a pull request?

**Comment by can0199** [comment]
Done.
[https://github.com/Tuurlijk/typo3scan/pull/18#issue-245823350](url)

**Comment by Tuurlijk** [comment]
Thx @can0199 !
