### ISSUE TITLE
[BUG] Scanning bigger project resolves in error.

### ISSUE THREAD

**Issue by tomasnorre** [Tuurlijk/typo3scan#19]
I have a project with 86 extensions, and when I want to scan the entire typo3conf/ext directory i get following error: 

```
$ typo3scan scan --only breaking --format markdown --target 8 . > ../report.md

In Name.php line 222:

  Name cannot be empty

scan [-t|--target [TARGET]] [-o|--only [ONLY]] [-f|--format [FORMAT]] [-r|--reportFile [REPORTFILE]] [--templatePath [TEMPLATEPATH]] [--] <path>
```

Any ideas what could cause this? When I do every single extension manually, every single on works.

But I would prefer a project total overview. 

Thanks in advance.

**Comment by Tuurlijk** [comment]
I'll take a look.

In the meantime, try something like:

```
cd typo3conf/ext
for e in `ls -1`;
do
    php ./typo3scan.phar scan --format html  ~/typo3conf/ext/$e > ~/tmp/reports/$e.html;
done
```

**Comment by tomasnorre** [comment]
That gives me the same error.

I'll check again, sounds more like a problem on my side then.

**Comment by tomasnorre** [comment]
I have found the extension cause the problem, but yet not the reason.. 

I've tried to search for Name.php file, but no file with this name exists within the extension. 

I don't find a file with the name `Name.php` in the typo3scan nor in the scanner repository from you. 

So funny where the error is coming from, and what's triggering it.

**Comment by tomasnorre** [comment]
The problem is on our side. 

We have done some b#!%€#"! dependency management in the time before composer.
