### ISSUE TITLE
Binary is missing when installing with composer

### ISSUE THREAD

**Issue by tomasnorre** [Tuurlijk/typo3scan#2]
Thanks for a super awesome tool.

When installing with composer the binary is missing:

```
$ ls -l vendor/bin/
doctrine-dbal -> ../doctrine/dbal/bin/doctrine-dbal
fluid -> ../typo3fluid/fluid/bin/fluid
php-parse -> ../nikic/php-parser/bin/php-parse
phpunit -> ../phpunit/phpunit/phpunit
typo3cms -> ../helhum/typo3-console/typo3cms
``` 

Did I forget something?

**Comment by Tuurlijk** [comment]
Hi Tomas,

What are the steps you are using to install it using composer?

**Comment by tomasnorre** [comment]
Hi,
I have a TYPO3 Project already with composer so I am doing following to add the TYPO3scan:
```
$ composer config minimum-stability dev
$ composer config repositories.tuurlijk-scanner vcs https://github.com/Tuurlijk/scanner
$ composer require --update-no-dev  "michielroos/typo3scan:*"
```

**Comment by Tuurlijk** [comment]
Thx,

Should be fixed with f6dd995a009499499ac1f50942403ef90e4b774c

**Comment by tomasnorre** [comment]
As mentioned in #4 by @jpmschuler it not working.. the binary is there, but autoloading is failing.. 
I've tried following after the install:

```
$ composer du 
$ composer install --no-dev
```

but none refreshed the autoloading in a prober state.

**Comment by Tuurlijk** [comment]
`composer du` . . . nice one. Didn't know that shortcut.

Did the last commit fix the autoloading?

**Comment by tomasnorre** [comment]
It's works.. 

Thanks a lot for fixing it this fast.
