### ISSUE TITLE
[FEATURE] Findings returns with exit != 0 in cli

### ISSUE THREAD

**Issue by tomasnorre** [Tuurlijk/typo3scan#24]
I would like to have the possibility to run this tool within my CI process, and for that I need an exit different than exit 0; so that the job will fail on findings.

What do you think about the idea? Would be happy to help implement, test, review etc.

**Comment by mbrodala** [comment]
@tomasnorre This has been added with #39 and made default with https://github.com/Tuurlijk/typo3scan/commit/46f8f002c837bfdd2a86a9eacc70e8a3e3c9740a now.

@Tuurlijk I guess this can be closed. ;-)

**Comment by Tuurlijk** [comment]
Yes, but still needs a release. Keeping it open as reminder / TODO. Need to do a release of this repo with just the phar file so composer install can be done in bin dir. And move the sources that are now in here to another repo. typo3scan-src or something. just like phpstan.

**Comment by Tuurlijk** [comment]
Fixed with release 1.7.2

**Comment by mbrodala** [comment]
Thanks for the release!
