### ISSUE TITLE
HTML Report CSS?

### ISSUE THREAD

**Issue by tomasnorre** [Tuurlijk/typo3scan#3]
Hi,

Do I need to setup anything else besides templatePath to get the styles HTML reports? 
Mine is still looking plan simple unstyled :)

**Comment by Tuurlijk** [comment]
You can specify your styles inside the head section of your template or link to a publicly accessible version of your css from the template.

**Comment by tomasnorre** [comment]
Ok.. But even the default styling that you have added directly in the Html.twig template is not pressent. 
![typo3scan-html-report-no-styling](https://user-images.githubusercontent.com/1212481/45619063-32726600-ba78-11e8-8d90-5a4ca049407e.png)

**Comment by tomasnorre** [comment]
This due to some issue with my jenkins setup, doing it with jenkins, it works like a charm. 

Will look into this.
