### ISSUE TITLE
[FEATURE] Add support for TYPO3 10 

### ISSUE THREAD

**Issue by tomasnorre** [Tuurlijk/typo3scan#30]
I know that TYPO3 10 isn't LTS yet, but there shouldn't be more breaking changes introduced. 

It would be nice if the scanner could help me identify problems regarding breaking and deprecation for version 10 as well.

Thanks

**Comment by sbaghdadi** [comment]
After the release of TYPO3 10 I would love to see an update of this tool because we do use it often for upgrading projects. Are there any plans for this?

**Comment by Tuurlijk** [comment]
Fixed thanks to @helhum
