### ISSUE TITLE
Add the property annotation matcher to the scan

### ISSUE THREAD

**Issue by AlexRitty** [Tuurlijk/typo3scan#34]
In the MichielRoos\TYPO3Scan\Service\ScannerService  class, the matcher Matcher\PropertyAnnotationMatcher::class is missing.

**Comment by Tuurlijk** [comment]
Can you provide a patch?

**Comment by AlexRitty** [comment]
Sorry, I did not manage to compile the .phar with the last typo3scan
version. So I didn't propose any patches.
But I noted that the V9 matcher list in your ScannerService is note up to
date. The PropertyAnnotationMatcher is Missing.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le dim. 29 mars 2020 à 15:19, Michiel Roos <notifications@github.com> a
écrit :

**Comment by Tuurlijk** [comment]
You should be able to run the code without building a phar file as noted here: https://github.com/Tuurlijk/typo3scan#run-the-typo3scan-tool

**Comment by Tuurlijk** [comment]
You mean in the bundle definition!

**Comment by Tuurlijk** [comment]
Fixed. Thx for reporting. New release is out
